DLS-6358:
hmrc/help-to-save-frontend pull request #1034
Opened 2023-08-15 10:35 UTC by karolina-zaborska

2023-08-15 10:56 UTC, LAJW submitted a review, later dismissed

2023-08-21 17:05 UTC, johno1985 commented on test/uk/gov/hmrc/helptosavefrontend/repo/SessionStoreSpec.scala
> +    //toedit
remove this comment

2023-08-21 17:05 UTC, johno1985 commented on test/uk/gov/hmrc/helptosavefrontend/repo/SessionStoreSpec.scala
> +    //toedit
remove this comment

2023-08-21 17:05 UTC, johno1985 commented on test/uk/gov/hmrc/helptosavefrontend/repo/SessionStoreSpec.scala
> +//toedit
remove this comment

2023-08-21 17:06 UTC, johno1985 requested changes
comments left

2023-08-21 17:19 UTC, johno1985 approved these changes

2023-08-22 10:40 UTC, LAJW approved these changes

2023-08-22 10:40 UTC, LAJW commented on build.sbt
> +    Wart.GlobalExecutionContext
I think Var, ListAppend, AsInstanceOf, NonUnitStatements, ,SeqApply and Equals are worth investigating.

2023-08-22 12:52 UTC, merged