DLS-3462 Welsh changes
hmrc/help-to-save-frontend pull request #918
Opened 2020-11-06 11:46 UTC by gavinharris43

2020-11-09 14:27 UTC, lutnos requested changes
We should not have to have our own versions of month names in our English messages file

2020-11-09 14:27 UTC, lutnos commented on conf/messages
> +
I'm confused, why are these here?

2020-11-09 14:45 UTC, gavinharris43 commented on conf/messages
> +
Removed

2020-11-09 14:54 UTC, gavinharris43 commented on conf/messages
> +
Removed.

2020-11-09 14:59 UTC, lutnos approved these changes
Great, thanks

2020-12-01 12:21 UTC, merged

2020-12-07 14:50 UTC, lutnos commented
Release requires deployment of help-to-save-frontend, blocked on  DLS-3252 Implement welsh accessibility statement file into HTS