DLS-3404 Added audit events
hmrc/help-to-save-frontend pull request #919
Opened 2020-11-17 16:06 UTC by gavinharris43

2020-11-17 17:02 UTC, lutnos reviewed
... plus I think we may have a problem in Travis, the job has bee queued for about an hour.  Not sure what to do about that.  Let's hope the problem goes away, say overnight

2020-11-17 17:06 UTC, lutnos requested changes
Gavin, my earlier Comment was meant to be a Request changes!

2020-11-18 12:32 UTC, gavinharris43 commented on app/uk/gov/hmrc/helptosavefrontend/controllers/ReminderController.scala
> +                            HtsReminderUserCreatedEvent(HtsReminderUserCreated(Json.toJson(htsUserToBeUpdated)), request.uri),
done

2020-11-18 12:32 UTC, gavinharris43 commented on app/uk/gov/hmrc/helptosavefrontend/controllers/ReminderController.scala
> +                                userInfo.nino, userInfo.email.getOrElse("")), request.uri),
done

2020-11-18 12:33 UTC, gavinharris43 commented on app/uk/gov/hmrc/helptosavefrontend/controllers/ReminderController.scala
> +                              HtsReminderUserUpdatedEvent(HtsReminderUserUpdated(Json.toJson(htsUserToBeUpdated)), request.uri),
done

2020-11-18 12:35 UTC, lutnos approved these changes

2020-11-24 16:16 UTC, merged